// <auto-generated/>
// GlobalSuppressions.cs
// Gilt für das gesamte Assembly "System.Collections.Generic.Missings"

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Naming",
    "CA1710:Bezeichner müssen ein korrektes Suffix aufweisen",
    Justification = "Missings folgt STL-ähnlichen Collection-Namen",
    Scope = "namespace",
    Target = "~N:System.Collections.Generic.Missings")]

[assembly: SuppressMessage(
    "Naming",
    "CA1711:Bezeichner dürfen kein falsches Suffix aufweisen",
    Justification = "Missings verwendet eigene Collection-Suffixe",
    Scope = "namespace",
    Target = "~N:System.Collections.Generic.Missings")]

[assembly: SuppressMessage(
    "Naming",
    "CA1716:Bezeichner dürfen nicht mit Schlüsselwörtern übereinstimmen",
    Justification = "Missings nutzt bewusst kurze, STL-ähnliche Namen",
    Scope = "namespace",
    Target = "~N:System.Collections.Generic.Missings")]

[assembly: SuppressMessage(
    "Design",
    "CA1051:Sichtbare Instanzfelder nicht deklarieren",
    Justification = "Missings erlaubt sichtbare Felder für Performance/Engine-Design",
    Scope = "namespace",
    Target = "~N:System.Collections.Generic.Missings")]

[assembly: SuppressMessage(
    "Usage",
    "CA2208:Argumentausnahmen korrekt instanziieren",
    Justification = "Missings nutzt eigene Exception-Patterns",
    Scope = "namespace",
    Target = "~N:System.Collections.Generic.Missings")]
[assembly: SuppressMessage(
    "Naming", 
    "CA1711:Bezeichner dürfen kein falsches Suffix aufweisen", 
    Justification = "<Ausstehend>", 
    Scope = "namespace", Target = "~N:System.Collections.Generic.Missings")]
