<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RoseLeDark.Collections.Missings</AssemblyName>
    <Title>RoseLeDark.Collections.Missings</Title>
    <Company>Amber-Sophia Schröck</Company>
    <PackageIcon>SystemEx.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>0.90.1785</AssemblyVersion>
    <FileVersion>0.90.1785</FileVersion>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <Description>RoseLeDark.Collections.Missings 

SystemEx is a modular, low‑level extension framework for .NET providing
deterministic numeric types, high‑performance collections, STL‑style
algorithms, advanced color models, random engines, interop utilities,
threading primitives, and bit‑level tools.

It is designed for engine development, simulation, rendering pipelines,
compiler tooling, and any environment requiring predictable, allocation‑aware,
byte‑level control.

&gt; **Design Note**
&gt;
&gt; SystemEx is intentionally structured to avoid deep cross‑dependencies between
&gt; modules. In several areas — especially within the collection and numeric
&gt; subsystems — certain data structures appear in multiple forms or are implemented
&gt; more than once (for example, `Map&lt;TKey, TValue&gt;` using `Pair&lt;TKey, TValue&gt;[]`
&gt; instead of reusing `Vector&lt;Pair&lt;...&gt;&gt;`).  
&gt; 
&gt; This duplication is deliberate. SystemEx is a large, highly generic low‑level
&gt; framework, and isolating components prevents errors or design changes in one
&gt; subsystem from propagating unpredictably into others. This approach keeps the
&gt; library stable, easier to debug, and safer to extend, especially when working
&gt; with complex iterator models, custom numeric types, and engine‑oriented memory
&gt; layouts.
&gt;
&gt; SystemEx is a personal hobby project developed by a single intersex author; my pronouns 
&gt; are dey/deren/dem/dem. While I aim for correctness, determinism, and clean architecture, 
&gt; not every issue may be visible immediately, and responses or fixes may occasionally
&gt; be delayed. Constructive feedback, improvement ideas, and technical discussions 
&gt; are always welcome.

## ✨ Core Philosophy

SystemEx follows these principles:

- **Deterministic behavior**  
- **Zero‑magic, zero‑hidden‑allocation APIs**  
- **Explicit numeric semantics** (Half16, Ratio, Fast_Int, Fast_Byte)  
- **STL‑inspired algorithms and iterators**  
- **Modular namespaces** for clean separation  
- **Engine‑oriented design** (Random, Threading, Runtime, Drawing)  
- **Interop‑friendly** (Linux, macOS, Windows dynamic loading)  </Description>
    <PackageTags>collections;generic;map;multimap;cache;buffer;datastructures;lowlevel;cache;pair;nodes;multimap;tuple;triple</PackageTags>
    <Copyright>© 2026 KSchattenfeld - Licensed under the EUPL</Copyright>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.90.1785</Version>
    <PackageProjectUrl>https://roseledark.github.io/SystemEx.Docs/</PackageProjectUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Amber-Sophia Schröck</Authors>
    <PackageId>RoseLeDark.Collections.Missings</PackageId>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>RoseLeDark.Collections.Missings.snk</AssemblyOriginatorKeyFile>
    <Product>RoseLeDark.Collections.Missings</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>SystemEx</RootNamespace>
    <PackageReleaseNotes>## [0.90.1785] 18.08.2026 intern Preview for 1.0 -&gt; Lacking
### Added
- Added Half16hb (Google Half 16 floa type) and basic structs for more float types
- Added:
  - `vec2h` (Half16) and `vec2hb` (Half16b)
  - `vec3h` (Half16) and `vec3hb` (Half16b)
  - `vec4h` (Half16) and `vec4hb` (Half16b)
- Added conversion from Float to Half16 and Half16b and to float
- Added professional low‑level bit‑span-types `BitIntSpan`, `BitLongSpan` unsigned and signed version in FlexSpan style with reverse, ringbuffer and AsSpan System mode. 
  Becarful by Ring mode 
- Added `SystemEx.Numeric.Ratio`: Represents a rational number using a signed 64‑bit numerator and denominator. A Ratio stores an exact fractional value
  without automatic reduction. This allows the representation of structural fractions such as gear ratios.
- Added:
  - `vec2r` (Ratio)
  - `vec3r` (Ratio) 
  - `vec4r` (Ratio) 
- Added `SystemEx.MathR` for Ratio Math Utils with: 
    - `Pow`: Raises a ratio to an integer power exactly.
    - `DegreesToRadians`: Converts degrees to radians.
    - `RadiansToDegrees`: Converts radians to degrees.
    - `DegreesToTurns`: Converts degrees to turns (full rotations). deg / 360;
    - `TurnsToDegrees`: Converts turns (full rotations) to degrees.
    - `Sign`: Returns the sign of this ratio as a interger. The result is -1, 0, or 1 depending on the value of the ratio.
    - `Abs`: Returns the absolute value of the giving ratio : ABS(Numerator), ABS(Denominator)
    - `Clamp`: Clamps this ratio between the specified minimum and maximum values.
    - `Min`, `Max`, `MinMax`:
    - `Sqrt` with new return Type Result: Computes the square root of a `SystemEx.Numeric.Ratio` and returns the result
  inside a `SystemEx.Result` object. The method distinguishes between
  rational and irrational square roots. 
- Added `SystemEx.Result`: Represents a flexible multi-value result container that can hold successful values, multiple 
  return objects, assertion messages, or exception information.
- Added `SystemEx.ResultBuilder`: Provides a fluent builder for constructing complex &lt;see cref="Result"/&gt;
 objects across multiple processing steps, compiler stages, or mathematical operations.
- Added `SystemEx.FlexSpan` View to all basic Types - int, long, float , double. Be careful with Ring Mode and Foreache without a break 
  condition.
- Added TupleMap&lt;T&gt;: A flexible tuple structure where the first element acts as a stable key and additional values are stored in an expandable object array, 
  enabling structured multi‑value mappings.
</PackageReleaseNotes>
    <AssemblyTitle>RoseLeDark.Collections.Missings</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Library</OutputType>
    <ApplicationIcon>Logo_256.ico</ApplicationIcon>
    <TargetFramework>net10.0</TargetFramework>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Collections\Generic\Missings\**" />
    <EmbeddedResource Remove="Collections\Generic\Missings\**" />
    <None Remove="Collections\Generic\Missings\**" />
  </ItemGroup>
  <ItemGroup>
	  <None Include="Examples\*.cs" Pack="true" PackagePath="Examples" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="Collections\Generic\BasicRope.cs" />
    <Compile Remove="Examples\AI\Main.cs" />
    <Compile Remove="Examples\AI\WinCopilotBackend.cs" />
    <Compile Remove="Examples\AI\WinCopilotBackendFunctionFactory.cs" />
    <Compile Remove="Examples\ExampleAIWindowsBackend.cs" />
    <Compile Remove="Examples\ExampleBitView.cs" />
    <Compile Remove="Examples\VectorFind.cs" />
    <Compile Remove="Examples\VectorSet.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Examples\AI\README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\AI\README_de.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\ExampleBitView.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\ExampleHasher.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\ExampleRamKernelAdd.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\VectorFind.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\VectorSet.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logo_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Examples\AI\Main.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Examples\AI\WinCopilotBackend.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Examples\AI\WinCopilotBackendFunctionFactory.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
