<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RoseLeDark.Collections.Missings</AssemblyName>
    <Title>RoseLeDark.Collections.Missings</Title>
    <Company>Amber-Sophia Schröck</Company>
    <PackageIcon>SystemEx.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>0.59.164</AssemblyVersion>
    <FileVersion>0.59.164</FileVersion>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <Description>RoseLeDark.Collections.Missings — Updated Description
A lightweight extension library providing additional generic collection types and utility structures missing in .NET.
Includes Vector&lt;T&gt;, FixedVector&lt;T&gt;, SortedArray&lt;T&gt;, Map&lt;TKey,TValue&gt;, SortedMap&lt;TKey,TValue&gt;, MultiMap&lt;TKey,TValue&gt;, Deque&lt;T&gt;, RingBuffer&lt;T&gt;, and tuple‑like helpers such as Pair&lt;T1,T2&gt; and Triple&lt;T1,T2,T3&gt;.

Provides extended numeric and color types including ColorRGB8, ColorRGB10, ColorRGB16, ColorHDR, ColorXYZ, and a unified Colors utility module.
Adds lightweight hash implementations for non‑cryptographic scenarios, supporting deterministic hashing for engine‑oriented data structures.

Designed as a minimal, allocation‑controlled complement to .NET’s built‑in collections, focusing on predictable behavior, simple APIs, and practical data structures commonly found in other ecosystems.</Description>
    <PackageTags>collections;generic;map;multimap;cache;buffer;datastructures;lowlevel;cache;pair;nodes;multimap;tuple;triple</PackageTags>
    <Copyright>© 2026 KSchattenfeld - Licensed under the EUPL</Copyright>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.59.164</Version>
    <PackageProjectUrl>https://roseledark.github.io/SystemEx.Docs/</PackageProjectUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Amber-Sophia Schröck</Authors>
    <PackageId>RoseLeDark.Collections.Missings</PackageId>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>RoseLeDark.Collections.Missings.snk</AssemblyOriginatorKeyFile>
    <Product>RoseLeDark.Collections.Missings</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>SystemEx</RootNamespace>
    <PackageReleaseNotes>## [0.59.164] 21.07.2026 -&gt; Lacking
### Remove
- 13.07.2026 Remove Array&lt;T&gt; old, FixedArray, SortedArray and Hashable 
### Changed
- 14.07.2026 Add to Vector&lt;T&gt; AsSet, AsMultiSet, AsUnorderedSet, AsUnorderedMultiSetSet, As AsFind and AsSearch as static functions, easer to use
- 15.07.2026 Rename FastVector to Array and add AsSet, AsMultiSet, AsUnorderedSet, AsUnorderedMultiSetSet, As AsFind and AsSearch as static functions, easer to use
- 21.07.2026 &lt;b&gt;FexedVector&lt;T&gt;&lt;/b&gt; renamed to &lt;b&gt;Array&lt;T&gt;&lt;/b&gt; and Update in all other objects
- 
## Added
- 15.07.2026 Add Fast_Types (Fast_Interger, Fast_Short, Fast_Byte, Fast_Float) 
- 21.07.2026 Add Seed Pipeline for SystemEx.Random System `ISeed`, `TimedBasedSeed`, `ValueBasedSeed` and SeedMixer for mixing multiple Seeds
- 21.07.2026 Add Slices View with SubSlices for JobQueueue in the Future with Worker Threads
- 21.07.2026 Add ` SubSlice` and `Slices` Provides a deterministic multi-thread slicing model over a container. A slice represents a continuous range of elements inside the container. Each slice can be exclusively owned by exactly one thread.
</PackageReleaseNotes>
    <AssemblyTitle>RoseLeDark.Collections.Missings</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Library</OutputType>
    <ApplicationIcon>Logo_256.ico</ApplicationIcon>
    <TargetFramework>net10.0</TargetFramework>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Collections\Generic\Missings\**" />
    <EmbeddedResource Remove="Collections\Generic\Missings\**" />
    <None Remove="Collections\Generic\Missings\**" />
  </ItemGroup>
  <ItemGroup>
	  <None Include="Examples\*.cs" Pack="true" PackagePath="Examples" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="Collections\Generic\BasicRope.cs" />
    <Compile Remove="Examples\ExampleAIWindowsBackend.cs" />
    <Compile Remove="Examples\VectorFind.cs" />
    <Compile Remove="Examples\VectorSet.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Examples\ExampleHasher.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\ExampleRamKernelAdd.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\VectorFind.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Examples\VectorSet.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logo_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Collections\Generic\BasicRope.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Examples\AI\Main.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Examples\AI\WinCopilotBackend.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
