<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>System.Collections.Generic.Missings</AssemblyName>
    <Title>$(AssemblyName)</Title>
    <Company>Amber-Sophia Schröck</Company>
    <PackageIcon>System.Collections.Generic.Extras.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>0.5.0</AssemblyVersion>
    <FileVersion>0.5.0</FileVersion>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <Description>Additional generic collection types missing in .NET.</Description>
    <PackageTags>collections;generic:stack;buffer;cache;utilities;map;MultiMap;Pair;Tuple;Generic;Array</PackageTags>
    <Copyright>© 2026 KSchattenfeld - Licensed under the EUPL</Copyright>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="System.Collections.Generic.Extras.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
