<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RoseLeDark.Collections.Missings</AssemblyName>
    <Title>RoseLeDark.Collections.Missings</Title>
    <PackageIcon>SystemEx.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageTags>collections;generic;map;multimap;cache;buffer;datastructures;lowlevel;cache;pair;nodes;multimap;tuple;triple;rcu;latch;atomic</PackageTags>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://roseledark.github.io/SystemEx.Docs/</PackageProjectUrl>
    <PackageId>RoseLeDark.Collections.Missings</PackageId>
    <Product>RoseLeDark.Collections.Missings</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <RootNamespace>SystemEx</RootNamespace>
    <AssemblyTitle>RoseLeDark.Collections.Missings</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Library</OutputType>
    <ApplicationIcon>Logo_256.ico</ApplicationIcon>
    <BaseOutputPath>..\bin\SystemEx</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>True</Deterministic>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Update="CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logo_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
