<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputPath>..\build\</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../nuget/version.txt"))</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Company>Amber-Sophia Schröck</Company>
    <Authors>Amber-Sophia Schröck</Authors>
    <Copyright>© 2026 KSchattenfeld - Licensed under the EUPL</Copyright>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\nuget\RoseLeDark.Collections.Missings.snk</AssemblyOriginatorKeyFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <Guid>91bb9a1e-fb8a-495a-930c-b21dd201bff7</Guid>
    <AssemblyName>RoseLeDark.Collections.Missings</AssemblyName>
    <Title>RoseLeDark.Collections.Missings</Title>
    <PackageIcon>Logo_256.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageTags>collections;generic;vector;multimap;datastructures;lowlevel;buffer;cache;</PackageTags>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://roseledark.github.io/SystemEx.Docs/</PackageProjectUrl>
    <PackageId>RoseLeDark.Collections.Missings</PackageId>
    <Product>RoseLeDark.Collections.Missings</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <RootNamespace>SystemEx</RootNamespace>
    <AssemblyTitle>RoseLeDark.Collections.Missings</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Platforms>AnyCPU;x64;x86;ARM32;ARM64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <IsTrimmable>true</IsTrimmable>
    <VerifyReferenceTrimCompatibility>true</VerifyReferenceTrimCompatibility>
    <Deterministic>true</Deterministic>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <Description>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../nuget/Readme.md"))</Description>
    <DelaySign>True</DelaySign>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../nuget/ReleaseNotes.md"))</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM32'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM32'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <IsPublishable>True</IsPublishable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Logo_256.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\MAINTAINERS.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\CONTRIBUTING.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\ARCHITECTURE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
      <None Include="..\Examples\*\*" Pack="true" PackagePath="\Examples\" />
  </ItemGroup>
  
</Project>
