<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RoseLeDark.Collections.Missings</AssemblyName>
    <Title>RoseLeDark.Collections.Missings</Title>
    <PackageIcon>SystemEx.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <Description>RoseLeDark.Collections.Missings 

SystemEx is a modular, low‑level extension framework for .NET providing
deterministic numeric types, high‑performance collections, STL‑style
algorithms, advanced color models, random engines, interop utilities,
threading primitives, and bit‑level tools.

It is designed for engine development, simulation, rendering pipelines,
compiler tooling, and any environment requiring predictable, allocation‑aware,
byte‑level control.

&gt; **Design Note**
&gt;
&gt; SystemEx is intentionally structured to avoid deep cross‑dependencies between
&gt; modules. In several areas — especially within the collection and numeric
&gt; subsystems — certain data structures appear in multiple forms or are implemented
&gt; more than once (for example, `Map&lt;TKey, TValue&gt;` using `Pair&lt;TKey, TValue&gt;[]`
&gt; instead of reusing `Vector&lt;Pair&lt;...&gt;&gt;`).  
&gt; 
&gt; This duplication is deliberate. SystemEx is a large, highly generic low‑level
&gt; framework, and isolating components prevents errors or design changes in one
&gt; subsystem from propagating unpredictably into others. This approach keeps the
&gt; library stable, easier to debug, and safer to extend, especially when working
&gt; with complex iterator models, custom numeric types, and engine‑oriented memory
&gt; layouts.
&gt;
&gt; SystemEx is a personal hobby project developed by a single intersex author; my pronouns 
&gt; are dey/deren/dem/dem. While I aim for correctness, determinism, and clean architecture, 
&gt; not every issue may be visible immediately, and responses or fixes may occasionally
&gt; be delayed. Constructive feedback, improvement ideas, and technical discussions 
&gt; are always welcome.

## ✨ Core Philosophy

SystemEx follows these principles:

- **Deterministic behavior**  
- **Zero‑magic, zero‑hidden‑allocation APIs**  
- **Explicit numeric semantics** (Half16, Ratio, Fast_Int, Fast_Byte)  
- **STL‑inspired algorithms and iterators**  
- **Modular namespaces** for clean separation  
- **Engine‑oriented design** (Random, Threading, Runtime, Drawing)  
- **Interop‑friendly** (Linux, macOS, Windows dynamic loading)  </Description>
    <PackageTags>collections;generic;map;multimap;cache;buffer;datastructures;lowlevel;cache;pair;nodes;multimap;tuple;triple;rcu;latch;atomic;</PackageTags>
    <RepositoryUrl>https://github.com/RoseLeDark/System.Collections.Generic.Missings.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://roseledark.github.io/SystemEx.Docs/</PackageProjectUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>RoseLeDark.Collections.Missings</PackageId>
    <Product>RoseLeDark.Collections.Missings</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <RootNamespace>SystemEx</RootNamespace>
    <PackageReleaseNotes>## [0.93.1957] 25.08.2026 intern Preview for 1.0 -&gt; Lacking
!!! VERY IMPORTEND UPDATE !!!

!! Very importend remnove AutoGrow Bug from All Collections !! PushBack and AutoGrow now Working !!

### Remove
- Marked Islocked in ILocked as Obsolete and add IsHeld in ILocked
- Remove IsHeld from ISpinLock
- Reomve bugs (Randown and other) 

### Added
- AtomicLock a SpinLock user mode running SpinLock with ThreadOwnerTrackingEnabled
- Add Running Examples - see github Examples
</PackageReleaseNotes>
    <AssemblyTitle>RoseLeDark.Collections.Missings</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Library</OutputType>
    <ApplicationIcon>Logo_256.ico</ApplicationIcon>
    <TargetFramework>net10.0</TargetFramework>
    <BaseOutputPath>..\bin\SystemEx</BaseOutputPath>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <IsAotCompatible>True</IsAotCompatible>
    <Deterministic>False</Deterministic>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Collections\Generic\Missings\**" />
    <Compile Remove="Examples\**" />
    <EmbeddedResource Remove="Collections\Generic\Missings\**" />
    <EmbeddedResource Remove="Examples\**" />
    <None Remove="Collections\Generic\Missings\**" />
    <None Remove="Examples\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Collections\Generic\BasicRope.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logo_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SystemEx.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
